### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wishdev** [qhwa/auto_response#8]
Would it be possible to add a License to this project? I would like to use the code from har.rb but I want to make sure I provide the appropriate attribution.

Thanks!

**Comment by qhwa** [comment]
Hi, this project is open under MIT license. Thanks for reminding me to add it to README.

**Comment by qhwa** [comment]
btw. What is `har.rb`?

**Comment by wishdev** [comment]
lib/ar/har.rb -> the code that creates a har file from a request/response

Thanks for adding the license
